//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMemeber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMemeber()
        {
            this.tBrowseHistory = new HashSet<tBrowseHistory>();
            this.tComment = new HashSet<tComment>();
            this.tMember_Wallat = new HashSet<tMember_Wallat>();
            this.tMyFavorite = new HashSet<tMyFavorite>();
            this.tMessage_Board = new HashSet<tMessage_Board>();
            this.tMessage = new HashSet<tMessage>();
            this.tMessage1 = new HashSet<tMessage>();
            this.tPhoto = new HashSet<tPhoto>();
            this.tRestaurant = new HashSet<tRestaurant>();
            this.tRestaurantOrders = new HashSet<tRestaurantOrders>();
        }
    
        public int fMemberID { get; set; }
        public string fMemeberName { get; set; }
        public string fEmail { get; set; }
        public string fPasswordConfirm { get; set; }
        public string fPassword { get; set; }
        public Nullable<int> fPhotoID { get; set; }
        public int fAreaID { get; set; }
        public string fAddress { get; set; }
        public string fLatitude { get; set; }
        public string fLongitude { get; set; }
        public System.DateTime fBirth { get; set; }
        public string fGender { get; set; }
        public System.DateTime fJoinDate { get; set; }
        public string fPhone { get; set; }
        public string fTel { get; set; }
        public string fCreditAccount { get; set; }
        public Nullable<int> fCollectionPoint { get; set; }
        public string fWalletTotalMoney { get; set; }
        public int fRoleID { get; set; }
        public Nullable<int> fReportsTo { get; set; }
        public Nullable<bool> fActivated { get; set; }
        public string fValidNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBrowseHistory> tBrowseHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComment { get; set; }
        public virtual tMember_Area tMember_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember_Wallat> tMember_Wallat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMyFavorite> tMyFavorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessage_Board> tMessage_Board { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessage> tMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessage> tMessage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPhoto> tPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurant> tRestaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantOrders> tRestaurantOrders { get; set; }
    }
}
