//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMessage_Board
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMessage_Board()
        {
            this.tMessage_Board1 = new HashSet<tMessage_Board>();
        }
    
        public int fMessageBoard_ID { get; set; }
        public System.DateTime fDatetime { get; set; }
        public int fFromID { get; set; }
        public int fToID { get; set; }
        public string fMessage { get; set; }
        public Nullable<int> fParentID { get; set; }
        public bool fRead { get; set; }
    
        public virtual tMemeber tMemeber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMessage_Board> tMessage_Board1 { get; set; }
        public virtual tMessage_Board tMessage_Board2 { get; set; }
        public virtual tRestaurant tRestaurant { get; set; }
    }
}
