//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant_FoodCustomizedCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurant_FoodCustomizedCategory()
        {
            this.tFood_CustomizedOption = new HashSet<tFood_CustomizedOption>();
            this.tRestaurant_Foods = new HashSet<tRestaurant_Foods>();
        }
    
        public int fCustomizedCategoryID { get; set; }
        public string fCustomizedCategoryName { get; set; }
        public Nullable<int> fParentID { get; set; }
        public System.DateTime fModifiedDate { get; set; }
        public string fCategoryDescription { get; set; }
        public Nullable<int> fRestaurantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFood_CustomizedOption> tFood_CustomizedOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurant_Foods> tRestaurant_Foods { get; set; }
    }
}
