//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant_Foods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurant_Foods()
        {
            this.tFood_FoodIngrident_Detail = new HashSet<tFood_FoodIngrident_Detail>();
            this.tPhoto = new HashSet<tPhoto>();
            this.tRestaurantOrder_Details = new HashSet<tRestaurantOrder_Details>();
            this.tRestaurantMeal_Detail = new HashSet<tRestaurantMeal_Detail>();
            this.tRestaurantMeal_Detail1 = new HashSet<tRestaurantMeal_Detail>();
        }
    
        public int fFoodID { get; set; }
        public string fFoodName { get; set; }
        public Nullable<int> fCustomizedCategoryID { get; set; }
        public int fRestaurantID { get; set; }
        public string fRemark { get; set; }
        public decimal fPrice { get; set; }
        public Nullable<decimal> fCost { get; set; }
        public bool fAvailable { get; set; }
        public Nullable<decimal> fDiscount { get; set; }
        public bool fRaw_Cooked { get; set; }
        public Nullable<System.DateTime> fModifiedDate { get; set; }
        public Nullable<int> fPhotoID { get; set; }
        public System.TimeSpan fCookTime { get; set; }
        public int fCategoryID { get; set; }
        public bool fIsMeal { get; set; }
        public string fFoodDescription { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFood_FoodIngrident_Detail> tFood_FoodIngrident_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPhoto> tPhoto { get; set; }
        public virtual tRestaurant tRestaurant { get; set; }
        public virtual tRestaurant_FoodCustomizedCategory tRestaurant_FoodCustomizedCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantOrder_Details> tRestaurantOrder_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantMeal_Detail> tRestaurantMeal_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantMeal_Detail> tRestaurantMeal_Detail1 { get; set; }
    }
}
