//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant_Category_Details
    {
        public int fId { get; set; }
        public Nullable<int> fRestaurantID { get; set; }
        public Nullable<int> fRestaurant_CategoryID { get; set; }
        public string fBuildDate { get; set; }
    
        public virtual tRestaurant tRestaurant { get; set; }
        public virtual tRestaurant_Category tRestaurant_Category { get; set; }
    }
}
