//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant_PaymentWay_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurant_PaymentWay_Detail()
        {
            this.tRestaurant = new HashSet<tRestaurant>();
        }
    
        public int fID { get; set; }
        public int fRestaurantID { get; set; }
        public int fPaymentwayID { get; set; }
    
        public virtual tPaymentWay tPaymentWay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurant> tRestaurant { get; set; }
    }
}
