//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurantOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurantOrders()
        {
            this.tRestaurantOrder_Details = new HashSet<tRestaurantOrder_Details>();
        }
    
        public int fOrderID { get; set; }
        public int fMemberID { get; set; }
        public int fRestaurantID { get; set; }
        public System.DateTime fOrderDatetime { get; set; }
        public System.TimeSpan fTakeoutTime { get; set; }
        public System.TimeSpan fDeliveryTime { get; set; }
        public string fDeliveryAddress { get; set; }
        public string Company_Tax_ID { get; set; }
        public string fDeliverName { get; set; }
        public int fPayment { get; set; }
        public string fRemark { get; set; }
        public int fOrderStatus { get; set; }
        public Nullable<int> fStar { get; set; }
        public string fComment { get; set; }
        public Nullable<bool> fIsHistory { get; set; }
        public Nullable<int> fCustomizedOptionID { get; set; }
        public Nullable<bool> fIsDelay { get; set; }
    
        public virtual tMemeber tMemeber { get; set; }
        public virtual tPaymentWay tPaymentWay { get; set; }
        public virtual tRestaurant tRestaurant { get; set; }
        public virtual tRestaurant_Order_States tRestaurant_Order_States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantOrder_Details> tRestaurantOrder_Details { get; set; }
    }
}
