//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliveryTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurant_Category()
        {
            this.tRestaurant_Category_Details = new HashSet<tRestaurant_Category_Details>();
        }
    
        public int fRestaurant_CategoryID { get; set; }
        public string fCategory_Name { get; set; }
        public string fCategory_Description { get; set; }
        public string fBuildDate { get; set; }
        public byte[] fImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurant_Category_Details> tRestaurant_Category_Details { get; set; }
    }
}
